# nice yaml formatter: https://mtp.tools/formatters/yaml-formatter

site_name: Study Notes @ GTCafe (V1)
site_url: "https://study-notes.gtcafe.com/v1"
repo_url: "https://github.com/rickhw/study-notes.gtcafe.com/tree/v1"
edit_uri: "edit/v1/src/"
docs_dir: "docs"

# ----------------------------------------------------------------

nav:
  - "Home": "https://study-notes.gtcafe.com"
  - "Index":
    - "Overview": index.md
    - "ChangeLog": changelog.md
    - "排版": principle.md
  # - "Springboot":
  #   - "Validation": "springboot/validation.md"
  # - "Mechanism":
  #   - "Overview": "api/mechanism/overview.md"
  #   - "Async Comm": "api/mechanism/async-comm.md"
  # - "Development":
  #   - "Overview": "api/development/overview.md"
  #   - "Code Generator": "api/development/codegen.md"
  # - "Architecture":
  #   - "Overview": "api/arch/overview.md"
  #   - "API Gateway": "api/arch/api-gateway.md"


# ----------------------------------------------------------------

theme:
  name: material
  palette:
    primary: "custom"
    accent: "indigo"
  features:
    - content.tabs.link

    # enable navigation, https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.expand
    - navigation.path

markdown_extensions:
  ## enable content tabs: https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
     alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

# ----------------------------------------------------------------

extra:
  version:
    provider: mike


extra_css:
  - stylesheets/extra.css